version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1-
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "rails"
        versions: ["< 5.2", "< 6.0"]
    rebase-strategy: auto
